all:
  children:
    xui_servers:
      hosts:
        vpn-sg1:
          ansible_host: 203.0.113.10
          domain: sg1.example.com
          server_location: singapore
          panel_port: 2053
          panel_webpath: "/a8f3panel"
          xray_inbound_port: 443

        vpn-jp1:
          ansible_host: 203.0.113.20
          domain: jp1.example.com
          server_location: japan
          panel_port: 2053
          panel_webpath: "/x91cpanel"
          xray_inbound_port: 443

        vpn-us1:
          ansible_host: 203.0.113.30
          domain: us1.example.com
          server_location: usa
          panel_port: 2053
          panel_webpath: "/qz7mpanel"
          xray_inbound_port: 443

      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3
